// Mocks generated by Mockito 5.4.6 from annotations
// in neuropean/test/core/abstraction/native_bridge_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:neuropean/core/abstraction/domain/entities/service_result.dart'
    as _i2;
import 'package:neuropean/core/abstraction/domain/repositories/i_native_bridge.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeServiceResult_0<T1> extends _i1.SmartFake
    implements _i2.ServiceResult<T1> {
  _FakeServiceResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [INativeBridge].
///
/// See the documentation for Mockito's code generation for more information.
class MockINativeBridge extends _i1.Mock implements _i3.INativeBridge {
  MockINativeBridge() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ServiceResult<T>> invokeMethod<T>(
    String? method, [
    dynamic arguments,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#invokeMethod, [method, arguments]),
            returnValue: _i4.Future<_i2.ServiceResult<T>>.value(
              _FakeServiceResult_0<T>(
                this,
                Invocation.method(#invokeMethod, [method, arguments]),
              ),
            ),
          )
          as _i4.Future<_i2.ServiceResult<T>>);

  @override
  _i4.Stream<T> receiveBroadcastStream<T>(
    String? channelName, [
    dynamic arguments,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#receiveBroadcastStream, [
              channelName,
              arguments,
            ]),
            returnValue: _i4.Stream<T>.empty(),
          )
          as _i4.Stream<T>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
